# Generated by Django 5.0.14 on 2026-02-01 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_plate', models.CharField(db_index=True, max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('STOLEN', 'Stolen'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vehicle Registration',
                'verbose_name_plural': 'Vehicle Registrations',
                'db_table': 'vehicle_registrations',
            },
        ),
    ]
