# Generated by Django 5.0 on 2026-02-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_lookup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='status',
        ),
    ]
