# Generated by Django 5.0 on 2026-02-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_lookup', '0002_remove_vehicleregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregistration',
            name='license_points',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='license_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20),
        ),
    ]
