# Generated by Django 5.0.14 on 2026-02-01 15:57

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('frame_number', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('box_coordinates', models.JSONField()),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('altitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detections',
                'ordering': ['-timestamp'],
            },
        ),
    ]
