# Generated by Django 5.0.14 on 2026-02-01 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detections', '0001_initial'),
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='drones.drone'),
        ),
    ]
