# Generated by Django 5.0.14 on 2026-02-01 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detections', '0002_initial'),
        ('patrols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='patrol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='patrols.patrol'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['drone', '-timestamp'], name='detections_drone_i_5e998f_idx'),
        ),
    ]
