# Generated by Django 5.0 on 2026-02-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0003_initial'),
        ('drones', '0002_initial'),
        ('patrols', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detection',
            constraint=models.UniqueConstraint(fields=('patrol', 'frame_number', 'drone'), name='unique_patrol_frame_drone'),
        ),
    ]
