# Generated by Django 5.0.14 on 2026-02-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='track_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
