# Generated by Django 5.0 on 2026-02-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0004_detection_unique_patrol_frame_drone'),
        ('drones', '0002_initial'),
        ('patrols', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detection',
            name='unique_patrol_frame_drone',
        ),
        migrations.AddConstraint(
            model_name='detection',
            constraint=models.UniqueConstraint(condition=models.Q(('patrol__isnull', False)), fields=('patrol', 'frame_number', 'drone'), name='unique_patrol_frame_drone'),
        ),
        migrations.AddConstraint(
            model_name='detection',
            constraint=models.UniqueConstraint(condition=models.Q(('patrol__isnull', True)), fields=('frame_number', 'drone'), name='unique_frame_drone_no_patrol'),
        ),
    ]
