# Generated by Django 5.0 on 2026-02-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0006_remove_detection_unique_patrol_frame_drone_and_more'),
        ('drones', '0002_initial'),
        ('patrols', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detection',
            name='unique_patrol_frame_drone_track',
        ),
        migrations.RemoveConstraint(
            model_name='detection',
            name='unique_frame_drone_no_patrol_track',
        ),
        migrations.AddConstraint(
            model_name='detection',
            constraint=models.UniqueConstraint(condition=models.Q(('patrol__isnull', False)), fields=('patrol', 'drone', 'track_id'), name='unique_patrol_drone_track'),
        ),
        migrations.AddConstraint(
            model_name='detection',
            constraint=models.UniqueConstraint(condition=models.Q(('patrol__isnull', True)), fields=('drone', 'track_id'), name='unique_drone_track_no_patrol'),
        ),
    ]
