# Generated by Django 5.0 on 2026-02-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0007_remove_detection_unique_patrol_frame_drone_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='image_snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='detections/'),
        ),
    ]
