# Generated by Django 5.0.14 on 2026-02-01 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle_lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('safe_driving_points', models.IntegerField(default=0)),
                ('last_observation', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_score', to='vehicle_lookup.vehicleregistration')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LotteryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('draw_date', models.DateField()),
                ('pool_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('minimum_points', models.IntegerField(default=10, help_text='Minimum compliance points required to enter')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DRAWN', 'Drawn'), ('PAID', 'Paid')], default='OPEN', max_length=20)),
                ('warnings', models.TextField(blank=True, help_text='Any issues during draw')),
                ('winners', models.ManyToManyField(blank=True, related_name='lottery_wins', to='vehicle_lookup.vehicleregistration')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
