# Generated by Django 5.0.14 on 2026-02-01 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drones', '0001_initial'),
        ('patrols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('rtsp_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('frame_rate', models.IntegerField(default=30)),
                ('resolution', models.CharField(default='1920x1080', max_length=20)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='drones.drone')),
            ],
            options={
                'db_table': 'video_streams',
            },
        ),
        migrations.CreateModel(
            name='StreamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('frames_processed', models.IntegerField(default=0)),
                ('kafka_topic', models.CharField(max_length=100)),
                ('patrol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stream_sessions', to='patrols.patrol')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='stream_ingestion.videostream')),
            ],
            options={
                'db_table': 'stream_sessions',
                'indexes': [models.Index(fields=['stream', '-start_time'], name='stream_sess_stream__adf768_idx')],
            },
        ),
    ]
