# Generated by Django 5.0 on 2026-03-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videostream',
            name='rtsp_url',
        ),
    ]
