# Generated by Hand on 2026-04-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_ingestion', '0002_remove_videostream_rtsp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostream',
            name='stream_mode',
            field=models.CharField(choices=[('LIVE', 'Live Feed'), ('SIMULATED', 'Simulated Video')], default='LIVE', max_length=20),
        ),
    ]
