# Generated by Django 4.2.7 on 2026-01-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_officer_user_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='badge_number',
        ),
        migrations.AddField(
            model_name='user',
            name='force_number',
            field=models.CharField(blank=True, help_text='Officer Force Number', max_length=50, null=True, unique=True),
        ),
    ]
