# Generated by Django 5.0 on 2026-02-07 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detections', '0002_initial'),
        ('patrols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('violation_type', models.CharField(default='SPEEDING', max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PROCESSED', 'Processed'), ('CITATION_SENT', 'Citation Sent'), ('DISMISSED', 'Dismissed')], default='NEW', max_length=20)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('video_clip', models.FileField(blank=True, null=True, upload_to='evidence/videos/')),
                ('image_snapshot', models.ImageField(blank=True, null=True, upload_to='evidence/images/')),
                ('evidence_meta', models.JSONField(blank=True, default=dict)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='violation', to='detections.detection')),
                ('patrol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='patrols.patrol')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
