# Generated by Django 5.0 on 2026-02-15 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_lookup', '0001_initial'),
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='vehicle_lookup.vehicleregistration'),
        ),
    ]
