# Generated by Django 5.0 on 2026-02-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0002_violation_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PROCESSED', 'Processed'), ('CITATION_SENT', 'Citation Sent'), ('DISMISSED', 'Dismissed'), ('PAID', 'Paid')], default='NEW', max_length=20),
        ),
    ]
