# Generated by Django 5.0 on 2026-02-15 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0003_alter_violation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='violation',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PROCESSED', 'Processed'), ('CITATION_SENT', 'Citation Sent'), ('DISMISSED', 'Dismissed'), ('PAID', 'Paid'), ('PARTIAL', 'Partial Payment')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='ViolationPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZIG', 'Zimbabwe Gold (ZiG)')], default='USD', max_length=10)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('WIRE_TRANSFER', 'Wire Transfer')], default='CASH', max_length=20)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='violations.violation')),
            ],
            options={
                'verbose_name': 'Violation Payment',
                'verbose_name_plural': 'Violation Payments',
                'db_table': 'violation_payments',
            },
        ),
    ]
