# Generated by Django 4.2.7 on 2026-01-15 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model_type', models.CharField(max_length=100)),
                ('max_speed', models.FloatField(default=0.0, help_text='Max speed in km/h')),
                ('battery_capacity', models.FloatField(default=100.0, help_text='Battery capacity in Wh')),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('PATROLLING', 'Patrolling'), ('RETURNING', 'Returning'), ('CHARGING', 'Charging'), ('MAINTENANCE', 'Maintenance')], default='IDLE', max_length=20)),
                ('current_battery_level', models.FloatField(default=100.0, help_text='Current battery percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(help_text='Altitude in meters')),
                ('speed', models.FloatField(help_text='Current speed in km/h')),
                ('battery_percentage', models.FloatField()),
                ('heading', models.FloatField(help_text='Heading in degrees')),
                ('signal_strength', models.FloatField(blank=True, help_text='Signal strength in dBm or percentage', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='drones.drone')),
            ],
            options={
                'verbose_name_plural': 'Telemetry Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
