# Generated by Django 5.0 on 2026-02-07 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='droneapikey',
            name='drone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='drones.drone'),
        ),
        migrations.AddField(
            model_name='dronestatus',
            name='drone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='drones.drone'),
        ),
        migrations.AddField(
            model_name='gpslocation',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to='drones.drone'),
        ),
        migrations.AddIndex(
            model_name='gpslocation',
            index=models.Index(fields=['drone', '-timestamp'], name='gps_locatio_drone_i_6ea882_idx'),
        ),
    ]
