# Generated by Django 5.0 on 2026-03-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droneapikey',
            name='key',
        ),
        migrations.AddField(
            model_name='droneapikey',
            name='hashed_key',
            field=models.CharField(default='', editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='droneapikey',
            name='prefix',
            field=models.CharField(default='', editable=False, max_length=16),
        ),
    ]
