# Generated by Django 5.0 on 2026-03-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_remove_droneapikey_key_droneapikey_hashed_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='droneapikey',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='droneapikey',
            name='name',
            field=models.CharField(default='Default Key', max_length=100),
        ),
        migrations.AlterField(
            model_name='droneapikey',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='drones.drone'),
        ),
        migrations.AlterField(
            model_name='droneapikey',
            name='hashed_key',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='droneapikey',
            name='prefix',
            field=models.CharField(editable=False, max_length=16),
        ),
    ]
