# Generated by Django 5.0 on 2026-04-07 13:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_alter_droneapikey_options_droneapikey_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='last_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
