# Generated by Django 5.0.14 on 2026-02-01 15:57

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_data', models.JSONField()),
                ('summary', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'analytics_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeatMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('hour', models.IntegerField()),
                ('metric_type', models.CharField(max_length=50)),
                ('location_grid', models.JSONField()),
                ('min_lat', models.FloatField()),
                ('max_lat', models.FloatField()),
                ('min_lon', models.FloatField()),
                ('max_lon', models.FloatField()),
            ],
            options={
                'db_table': 'heat_maps',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ALLOCATION', 'Resource Allocation'), ('SAFETY', 'Safety Improvement'), ('MAINTENANCE', 'Maintenance Needed'), ('POLICY', 'Policy Adjustment')], default='ALLOCATION', max_length=20)),
                ('confidence_score', models.FloatField(help_text='Confidence level 0.0 to 1.0')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrafficMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('drone_id', models.CharField(max_length=100)),
                ('vehicle_count', models.IntegerField(default=0)),
                ('car_count', models.IntegerField(default=0)),
                ('truck_count', models.IntegerField(default=0)),
                ('motorcycle_count', models.IntegerField(default=0)),
                ('bus_count', models.IntegerField(default=0)),
                ('average_speed', models.FloatField(default=0.0)),
                ('max_speed', models.FloatField(default=0.0)),
                ('min_speed', models.FloatField(default=0.0)),
                ('speed_variance', models.FloatField(default=0.0)),
                ('violation_count', models.IntegerField(default=0)),
                ('citation_count', models.IntegerField(default=0)),
                ('sample_size', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'traffic_metrics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrafficPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern_type', models.CharField(choices=[('peak_hour', 'Peak Hour'), ('congestion', 'Congestion Zone'), ('accident_prone', 'Accident Prone Area')], max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('days_of_week', models.JSONField()),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField(blank=True, null=True)),
                ('avg_vehicle_count', models.FloatField(default=0.0)),
                ('avg_speed', models.FloatField(default=0.0)),
                ('violation_rate', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('sample_size', models.IntegerField(default=0)),
                ('recommendations', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'traffic_patterns',
            },
        ),
    ]
