# Generated by Django 5.0.14 on 2026-02-01 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='heatmap',
            index=models.Index(fields=['date', 'hour'], name='heat_maps_date_597a32_idx'),
        ),
        migrations.AddIndex(
            model_name='heatmap',
            index=models.Index(fields=['metric_type', 'date'], name='heat_maps_metric__7980b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='heatmap',
            unique_together={('date', 'hour', 'metric_type')},
        ),
        migrations.AddIndex(
            model_name='trafficmetrics',
            index=models.Index(fields=['timestamp', 'location'], name='traffic_met_timesta_c92ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficmetrics',
            index=models.Index(fields=['drone_id', 'timestamp'], name='traffic_met_drone_i_bae05a_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficpattern',
            index=models.Index(fields=['pattern_type', 'confidence_score'], name='traffic_pat_pattern_f7107d_idx'),
        ),
    ]
