# Generated by Django 5.0 on 2026-02-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('violation_detected', 'Violation Detected'), ('patrol_started', 'Patrol Started'), ('patrol_ended', 'Patrol Ended'), ('low_battery', 'Low Battery'), ('stream_health', 'Stream Health'), ('mission_update', 'Mission Update'), ('system_alert', 'System Alert'), ('emergency', 'Emergency'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
